baseURL = "https://tuan-3531.github.io/AWS_INTERN/"
relativeURLs = false
canonifyURLs = true
defaultContentLanguage = "en"


theme = "hugo-theme-learn"

[outputs]
home = [ "HTML", "RSS", "JSON"]
page = ["HTML", "RSS"]

[params]
  themeVariant = "blue"
  editURL = ""
  description = ""
  author = "dangquoctuan12t1nh2022@gmail.com"
  showVisitedLinks = true
  disableBreadcrumb = false
  disableNextPrev = false

[Languages]
[languages.en]
title = "Internship Report"
weight = 1

[languages.en.params]
label = "English"

[languages.vi]
title = "Báo cáo thực tập"
weight = 2

[languages.vi.params]
label = "Tiếng Việt"

[[Languages.en.menu.shortcuts]]



[[Languages.vi.menu.shortcuts]]


  

[[Languages.en.menu.shortcuts]]
  name = "<i class='fab fa-facebook fa-fw'></i> AWS Study Group - Blog-1"
  url = "https://www.facebook.com/groups/660548818043427/user/100015108252190"
  weight = 10

[[Languages.vi.menu.shortcuts]]
  name = "<i class='fab fa-facebook fa-fw'></i> AWS Study Group - Blog-1"
  url = "https://www.facebook.com/groups/660548818043427/user/100015108252190"
  weight = 10

[[Languages.en.menu.shortcuts]]
  name = "<i class='fab fa-facebook fa-fw'></i> AWS Study Group - Blog-2"
  url = "https://web.facebook.com/groups/660548818043427/user/100029043690648"
  weight = 10

[[Languages.vi.menu.shortcuts]]
  name = "<i class='fab fa-facebook fa-fw'></i> AWS Study Group - Blog-2"
  url = "https://web.facebook.com/groups/660548818043427/user/100029043690648"
  weight = 10




[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true
  [markup.highlight]
    style = "monokai"
    lineNos = false
